### ISSUE TITLE
secure shared GitLab Runner setup for Docker Build

### ISSUE THREAD

**Issue by bbodenmiller** [schmunk42/docker-gitlab-runner#4]
Is this safe to run as secure shared GitLab Runner for Docker Build? See also https://gitlab.com/gitlab-org/gitlab-ce/issues/31379

**Comment by schmunk42** [comment]
If you're starting this runner with a mounted docker socket, it creates sibling containers on the host and you have full access to the Docker daemon from the builds.
So it's not really recommended to run this in a public setup.

This is a trade-off between caching, host-volumes, data-integrity, performance and security. But it should also be possible to specify the docker socket by `DOCKER_HOST`, but this would not solve all security issues and you're losing the option of using host-volumes.

**Comment by schmunk42** [comment]
added info to https://github.com/schmunk42/docker-gitlab-runner/blob/master/README.md#warning-important-information
